-- =====================================================================================
-- V1 — Identity, catalog, warehouses, inventory, cart.
--
-- Vendor-neutral SQL only: `BIGINT GENERATED BY DEFAULT AS IDENTITY` and plain
-- DECIMAL/VARCHAR/TIMESTAMP render identically on H2 (PostgreSQL mode) and PostgreSQL,
-- which is what makes the profile swap in application-postgres.yml a no-op.
--
-- Money is persisted as an (amount, currency) pair per the LLD; no floating point
-- anywhere in the schema.
-- =====================================================================================

-- ------------------------------------------------------------------ identity
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(190) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(120) NOT NULL,
    phone         VARCHAR(20),
    zone          VARCHAR(40),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE roles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(40) NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP   NOT NULL,
    CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

-- A warehouse staff member is scoped to exactly one warehouse; the join is deliberately
-- kept out of `users` so the catalog side of the model stays independent of fulfillment.
CREATE TABLE warehouses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(30)  NOT NULL,
    name       VARCHAR(120) NOT NULL,
    zone       VARCHAR(40)  NOT NULL,
    city       VARCHAR(80)  NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_warehouses_code UNIQUE (code)
);

CREATE TABLE warehouse_staff (
    user_id      BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, warehouse_id),
    CONSTRAINT fk_wh_staff_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_wh_staff_wh FOREIGN KEY (warehouse_id) REFERENCES warehouses (id)
);

-- ------------------------------------------------------------------ catalog
CREATE TABLE categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    slug       VARCHAR(140) NOT NULL,
    parent_id  BIGINT,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_categories_slug UNIQUE (slug),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
);

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(190)  NOT NULL,
    description VARCHAR(2000),
    brand       VARCHAR(90),
    status      VARCHAR(30)   NOT NULL,
    category_id BIGINT        NOT NULL,
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id)
);
CREATE INDEX idx_products_category ON products (category_id);
CREATE INDEX idx_products_status ON products (status);

CREATE TABLE product_variants (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT        NOT NULL,
    sku            VARCHAR(60)   NOT NULL,
    variant_name   VARCHAR(120)  NOT NULL,
    price_amount   DECIMAL(19,2) NOT NULL,
    price_currency VARCHAR(3)    NOT NULL,
    weight_grams   INTEGER       NOT NULL DEFAULT 0,
    active         BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP     NOT NULL,
    updated_at     TIMESTAMP     NOT NULL,
    CONSTRAINT uq_variants_sku UNIQUE (sku),
    CONSTRAINT fk_variants_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_variants_price_non_negative CHECK (price_amount >= 0)
);
CREATE INDEX idx_variants_product ON product_variants (product_id);

-- ------------------------------------------------------------------ inventory
-- The contended region of the whole system. `available` is deliberately NOT stored:
-- it is derived as (on_hand - reserved). A stored availability column is a second
-- source of truth and drifts under concurrency.
CREATE TABLE inventory_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id   BIGINT    NOT NULL,
    warehouse_id BIGINT    NOT NULL,
    on_hand      INTEGER   NOT NULL DEFAULT 0,
    reserved     INTEGER   NOT NULL DEFAULT 0,
    reorder_level INTEGER  NOT NULL DEFAULT 0,
    version      BIGINT    NOT NULL DEFAULT 0,
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL,
    CONSTRAINT uq_inventory_variant_warehouse UNIQUE (variant_id, warehouse_id),
    CONSTRAINT fk_inventory_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id),
    CONSTRAINT fk_inventory_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    -- The backstop for requirement #1. Even a logic bug that forgets to lock cannot
    -- persist an oversold row: the database refuses the write.
    CONSTRAINT ck_inventory_reserved_within_on_hand CHECK (reserved >= 0 AND on_hand >= 0 AND reserved <= on_hand)
);
CREATE INDEX idx_inventory_variant ON inventory_items (variant_id);

CREATE TABLE stock_reservations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference         VARCHAR(60) NOT NULL,
    order_id          BIGINT,
    inventory_item_id BIGINT      NOT NULL,
    variant_id        BIGINT      NOT NULL,
    warehouse_id      BIGINT      NOT NULL,
    quantity          INTEGER     NOT NULL,
    status            VARCHAR(30) NOT NULL,
    expires_at        TIMESTAMP   NOT NULL,
    settled_at        TIMESTAMP,
    created_at        TIMESTAMP   NOT NULL,
    updated_at        TIMESTAMP   NOT NULL,
    CONSTRAINT fk_reservation_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id),
    CONSTRAINT ck_reservation_qty_positive CHECK (quantity > 0)
);
CREATE INDEX idx_reservation_status_expiry ON stock_reservations (status, expires_at);
CREATE INDEX idx_reservation_reference ON stock_reservations (reference);
CREATE INDEX idx_reservation_order ON stock_reservations (order_id);

-- Append-only audit of every physical stock movement. Nothing updates this table.
CREATE TABLE stock_ledger_entries (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT      NOT NULL,
    movement_type     VARCHAR(40) NOT NULL,
    quantity_delta    INTEGER     NOT NULL,
    on_hand_after     INTEGER     NOT NULL,
    reserved_after    INTEGER     NOT NULL,
    reference         VARCHAR(60),
    note              VARCHAR(255),
    created_at        TIMESTAMP   NOT NULL,
    updated_at        TIMESTAMP   NOT NULL,
    CONSTRAINT fk_ledger_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id)
);
CREATE INDEX idx_ledger_item ON stock_ledger_entries (inventory_item_id);

-- ------------------------------------------------------------------ cart
CREATE TABLE carts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_carts_user UNIQUE (user_id),
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT    NOT NULL,
    variant_id BIGINT    NOT NULL,
    quantity   INTEGER   NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_cart_items_cart_variant UNIQUE (cart_id, variant_id),
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id),
    CONSTRAINT fk_cart_items_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id),
    CONSTRAINT ck_cart_items_qty_positive CHECK (quantity > 0)
);
