-- =====================================================================================
-- V2 — Pricing configuration (tax rates, discounts), orders, order lines, payments.
-- =====================================================================================

-- ------------------------------------------------------------------ tax
-- Rate resolution walks the category tree upward until a row is found, then falls back
-- to oms.pricing.default-tax-rate. Rates are fractions (0.18 = 18%), never percentages,
-- so no /100 ever appears in the pricing code.
CREATE TABLE tax_rates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT        NOT NULL,
    rate        DECIMAL(9,6)  NOT NULL,
    description VARCHAR(120),
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    CONSTRAINT uq_tax_rates_category UNIQUE (category_id),
    CONSTRAINT fk_tax_rates_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT ck_tax_rate_range CHECK (rate >= 0 AND rate <= 1)
);

-- ------------------------------------------------------------------ discounts
CREATE TABLE discounts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                    VARCHAR(40)   NOT NULL,
    description             VARCHAR(255),
    type                    VARCHAR(40)   NOT NULL,
    value                   DECIMAL(19,4) NOT NULL,
    max_discount_amount     DECIMAL(19,2),
    max_discount_currency   VARCHAR(3),
    min_order_value_amount  DECIMAL(19,2),
    min_order_value_currency VARCHAR(3),
    category_id             BIGINT,
    starts_at               TIMESTAMP     NOT NULL,
    ends_at                 TIMESTAMP     NOT NULL,
    usage_limit             INTEGER,
    per_customer_limit      INTEGER,
    times_redeemed          INTEGER       NOT NULL DEFAULT 0,
    active                  BOOLEAN       NOT NULL DEFAULT TRUE,
    version                 BIGINT        NOT NULL DEFAULT 0,
    created_at              TIMESTAMP     NOT NULL,
    updated_at              TIMESTAMP     NOT NULL,
    CONSTRAINT uq_discounts_code UNIQUE (code),
    CONSTRAINT fk_discounts_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT ck_discount_value_positive CHECK (value > 0),
    CONSTRAINT ck_discount_window CHECK (ends_at > starts_at)
);

-- ------------------------------------------------------------------ orders
CREATE TABLE orders (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number             VARCHAR(40)   NOT NULL,
    user_id                  BIGINT        NOT NULL,
    status                   VARCHAR(40)   NOT NULL,

    subtotal_amount          DECIMAL(19,2) NOT NULL,
    subtotal_currency        VARCHAR(3)    NOT NULL,
    discount_total_amount    DECIMAL(19,2) NOT NULL,
    discount_total_currency  VARCHAR(3)    NOT NULL,
    tax_total_amount         DECIMAL(19,2) NOT NULL,
    tax_total_currency       VARCHAR(3)    NOT NULL,
    shipping_fee_amount      DECIMAL(19,2) NOT NULL,
    shipping_fee_currency    VARCHAR(3)    NOT NULL,
    grand_total_amount       DECIMAL(19,2) NOT NULL,
    grand_total_currency     VARCHAR(3)    NOT NULL,
    refunded_total_amount    DECIMAL(19,2) NOT NULL,
    refunded_total_currency  VARCHAR(3)    NOT NULL,

    shipping_address_recipient_name VARCHAR(120) NOT NULL,
    shipping_address_line1           VARCHAR(190) NOT NULL,
    shipping_address_city            VARCHAR(80)  NOT NULL,
    shipping_address_zone            VARCHAR(40)  NOT NULL,
    shipping_address_postal_code     VARCHAR(20)  NOT NULL,
    shipping_address_phone           VARCHAR(20)  NOT NULL,

    discount_code            VARCHAR(40),
    placed_at                TIMESTAMP     NOT NULL,
    confirmed_at             TIMESTAMP,
    delivered_at             TIMESTAMP,
    cancelled_at             TIMESTAMP,
    cancellation_reason      VARCHAR(255),
    version                  BIGINT        NOT NULL DEFAULT 0,
    created_at               TIMESTAMP     NOT NULL,
    updated_at               TIMESTAMP     NOT NULL,
    CONSTRAINT uq_orders_number UNIQUE (order_number),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_orders_totals_non_negative CHECK (grand_total_amount >= 0 AND subtotal_amount >= 0)
);
CREATE INDEX idx_orders_user ON orders (user_id);
CREATE INDEX idx_orders_status ON orders (status);

-- Order lines are an immutable snapshot of the cart at checkout time: sku and product
-- name are copied, so a later catalog rename never rewrites history.
CREATE TABLE order_lines (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id               BIGINT        NOT NULL,
    variant_id             BIGINT        NOT NULL,
    sku                    VARCHAR(60)   NOT NULL,
    product_name           VARCHAR(190)  NOT NULL,
    variant_name           VARCHAR(120)  NOT NULL,
    quantity               INTEGER       NOT NULL,
    returned_quantity      INTEGER       NOT NULL DEFAULT 0,

    unit_price_amount      DECIMAL(19,2) NOT NULL,
    unit_price_currency    VARCHAR(3)    NOT NULL,
    line_subtotal_amount   DECIMAL(19,2) NOT NULL,
    line_subtotal_currency VARCHAR(3)    NOT NULL,
    line_discount_amount   DECIMAL(19,2) NOT NULL,
    line_discount_currency VARCHAR(3)    NOT NULL,
    line_tax_amount        DECIMAL(19,2) NOT NULL,
    line_tax_currency      VARCHAR(3)    NOT NULL,
    line_total_amount      DECIMAL(19,2) NOT NULL,
    line_total_currency    VARCHAR(3)    NOT NULL,
    tax_rate               DECIMAL(9,6)  NOT NULL,

    created_at             TIMESTAMP     NOT NULL,
    updated_at             TIMESTAMP     NOT NULL,
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_lines_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id),
    CONSTRAINT ck_order_lines_qty CHECK (quantity > 0 AND returned_quantity >= 0 AND returned_quantity <= quantity)
);
CREATE INDEX idx_order_lines_order ON order_lines (order_id);

ALTER TABLE stock_reservations
    ADD CONSTRAINT fk_reservation_order FOREIGN KEY (order_id) REFERENCES orders (id);

CREATE TABLE discount_redemptions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_id BIGINT        NOT NULL,
    user_id     BIGINT        NOT NULL,
    order_id    BIGINT        NOT NULL,
    saved_amount   DECIMAL(19,2) NOT NULL,
    saved_currency VARCHAR(3)    NOT NULL,
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    CONSTRAINT uq_redemption_order UNIQUE (order_id),
    CONSTRAINT fk_redemption_discount FOREIGN KEY (discount_id) REFERENCES discounts (id),
    CONSTRAINT fk_redemption_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_redemption_order FOREIGN KEY (order_id) REFERENCES orders (id)
);
CREATE INDEX idx_redemption_discount_user ON discount_redemptions (discount_id, user_id);

-- ------------------------------------------------------------------ payments
CREATE TABLE payments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT        NOT NULL,
    status            VARCHAR(30)   NOT NULL,
    method            VARCHAR(30)   NOT NULL,
    charged_amount     DECIMAL(19,2) NOT NULL,
    charged_currency   VARCHAR(3)    NOT NULL,
    gateway_reference VARCHAR(80),
    failure_reason    VARCHAR(255),
    authorized_at     TIMESTAMP,
    version           BIGINT        NOT NULL DEFAULT 0,
    created_at        TIMESTAMP     NOT NULL,
    updated_at        TIMESTAMP     NOT NULL,
    CONSTRAINT uq_payments_order UNIQUE (order_id),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id)
);
CREATE INDEX idx_payments_status ON payments (status);
