-- =====================================================================================
-- V3 — Fulfillment, returns/refunds, and the four infrastructure tables that carry no
-- business relationships (outbox, audit, notifications, idempotency).
-- =====================================================================================

-- ------------------------------------------------------------------ fulfillment
-- One shipment per (order, warehouse): a split allocation legitimately produces two
-- shipments, and warehouse staff must only ever see their own.
CREATE TABLE shipments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT      NOT NULL,
    warehouse_id    BIGINT      NOT NULL,
    status          VARCHAR(30) NOT NULL,
    tracking_number VARCHAR(60),
    packed_at       TIMESTAMP,
    shipped_at      TIMESTAMP,
    delivered_at    TIMESTAMP,
    version         BIGINT      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP   NOT NULL,
    updated_at      TIMESTAMP   NOT NULL,
    CONSTRAINT uq_shipment_order_warehouse UNIQUE (order_id, warehouse_id),
    CONSTRAINT fk_shipment_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_shipment_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id)
);
CREATE INDEX idx_shipment_warehouse_status ON shipments (warehouse_id, status);

-- ------------------------------------------------------------------ returns & refunds
CREATE TABLE return_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT      NOT NULL,
    status          VARCHAR(30) NOT NULL,
    reason          VARCHAR(40) NOT NULL,
    comment         VARCHAR(500),
    resolution_note VARCHAR(500),
    requested_at    TIMESTAMP   NOT NULL,
    resolved_at     TIMESTAMP,
    version         BIGINT      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP   NOT NULL,
    updated_at      TIMESTAMP   NOT NULL,
    CONSTRAINT fk_return_order FOREIGN KEY (order_id) REFERENCES orders (id)
);
CREATE INDEX idx_return_order ON return_requests (order_id);
CREATE INDEX idx_return_status ON return_requests (status);

CREATE TABLE return_lines (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_request_id BIGINT        NOT NULL,
    order_line_id     BIGINT        NOT NULL,
    quantity          INTEGER       NOT NULL,
    refund_amount     DECIMAL(19,2) NOT NULL,
    refund_currency   VARCHAR(3)    NOT NULL,
    created_at        TIMESTAMP     NOT NULL,
    updated_at        TIMESTAMP     NOT NULL,
    CONSTRAINT fk_return_line_request FOREIGN KEY (return_request_id) REFERENCES return_requests (id),
    CONSTRAINT fk_return_line_order_line FOREIGN KEY (order_line_id) REFERENCES order_lines (id),
    CONSTRAINT ck_return_line_qty CHECK (quantity > 0)
);
CREATE INDEX idx_return_line_request ON return_lines (return_request_id);

CREATE TABLE refunds (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id        BIGINT        NOT NULL,
    return_request_id BIGINT,
    status            VARCHAR(30)   NOT NULL,
    refunded_amount   DECIMAL(19,2) NOT NULL,
    refunded_currency VARCHAR(3)    NOT NULL,
    reason            VARCHAR(255),
    gateway_reference VARCHAR(80),
    settled_at        TIMESTAMP,
    created_at        TIMESTAMP     NOT NULL,
    updated_at        TIMESTAMP     NOT NULL,
    CONSTRAINT fk_refund_payment FOREIGN KEY (payment_id) REFERENCES payments (id),
    CONSTRAINT fk_refund_return FOREIGN KEY (return_request_id) REFERENCES return_requests (id),
    CONSTRAINT ck_refund_amount_positive CHECK (refunded_amount > 0)
);
CREATE INDEX idx_refund_payment ON refunds (payment_id);

-- ------------------------------------------------------------------ transactional outbox
-- Written inside the checkout transaction, dispatched after commit. This is what makes
-- "the downstream pipeline does not block checkout" survive a JVM crash.
CREATE TABLE outbox_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type     VARCHAR(80)   NOT NULL,
    aggregate_type VARCHAR(40)   NOT NULL,
    aggregate_id   BIGINT        NOT NULL,
    payload        VARCHAR(4000) NOT NULL,
    status         VARCHAR(20)   NOT NULL,
    attempts       INTEGER       NOT NULL DEFAULT 0,
    last_error     VARCHAR(1000),
    available_at   TIMESTAMP     NOT NULL,
    processed_at   TIMESTAMP,
    version        BIGINT        NOT NULL DEFAULT 0,
    created_at     TIMESTAMP     NOT NULL,
    updated_at     TIMESTAMP     NOT NULL
);
CREATE INDEX idx_outbox_status_available ON outbox_events (status, available_at);

-- At-least-once delivery means handlers can be re-invoked. This table is the
-- deduplication key: (event, handler) is attempted at most once successfully.
CREATE TABLE outbox_handler_executions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_event_id BIGINT      NOT NULL,
    handler_name    VARCHAR(80) NOT NULL,
    created_at      TIMESTAMP   NOT NULL,
    updated_at      TIMESTAMP   NOT NULL,
    CONSTRAINT uq_handler_execution UNIQUE (outbox_event_id, handler_name),
    CONSTRAINT fk_handler_execution_event FOREIGN KEY (outbox_event_id) REFERENCES outbox_events (id)
);

-- ------------------------------------------------------------------ audit
CREATE TABLE audit_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT,
    actor_email VARCHAR(190),
    action      VARCHAR(80)  NOT NULL,
    entity_type VARCHAR(40)  NOT NULL,
    entity_id   BIGINT,
    from_state  VARCHAR(40),
    to_state    VARCHAR(40),
    reason      VARCHAR(500),
    trace_id    VARCHAR(40),
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL
);
CREATE INDEX idx_audit_entity ON audit_events (entity_type, entity_id);
CREATE INDEX idx_audit_created ON audit_events (created_at);

-- ------------------------------------------------------------------ notifications
CREATE TABLE notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT        NOT NULL,
    channel      VARCHAR(30)   NOT NULL,
    subject      VARCHAR(190)  NOT NULL,
    body         VARCHAR(2000) NOT NULL,
    status       VARCHAR(20)   NOT NULL,
    sent_at      TIMESTAMP,
    created_at   TIMESTAMP     NOT NULL,
    updated_at   TIMESTAMP     NOT NULL,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_notification_user ON notifications (user_id);

-- ------------------------------------------------------------------ idempotency
-- The unique constraint is the concurrency control: two simultaneous submits with the
-- same key race on INSERT, and the loser waits then replays the winner's response.
CREATE TABLE idempotency_records (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key     VARCHAR(120)  NOT NULL,
    endpoint            VARCHAR(160)  NOT NULL,
    user_id             BIGINT,
    request_fingerprint VARCHAR(64)   NOT NULL,
    state               VARCHAR(20)   NOT NULL,
    response_status     INTEGER,
    response_body       VARCHAR(4000),
    created_at          TIMESTAMP     NOT NULL,
    updated_at          TIMESTAMP     NOT NULL,
    CONSTRAINT uq_idempotency_key_endpoint UNIQUE (idempotency_key, endpoint)
);
CREATE INDEX idx_idempotency_created ON idempotency_records (created_at);
